package DSL_UITesting.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;
import jetbrains.mps.smodel.adapter.ids.PrimitiveTypeId;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptAction = createDescriptorForAction();
  /*package*/ final ConceptDescriptor myConceptAndOfAciton = createDescriptorForAndOfAciton();
  /*package*/ final ConceptDescriptor myConceptClick = createDescriptorForClick();
  /*package*/ final ConceptDescriptor myConceptInputText = createDescriptorForInputText();
  /*package*/ final ConceptDescriptor myConceptLogicOfActions = createDescriptorForLogicOfActions();
  /*package*/ final ConceptDescriptor myConceptMaximize = createDescriptorForMaximize();
  /*package*/ final ConceptDescriptor myConceptOrOfAction = createDescriptorForOrOfAction();
  /*package*/ final ConceptDescriptor myConceptPageContainValidation = createDescriptorForPageContainValidation();
  /*package*/ final ConceptDescriptor myConceptTestCase = createDescriptorForTestCase();
  /*package*/ final ConceptDescriptor myConceptTestSuite = createDescriptorForTestSuite();
  /*package*/ final ConceptDescriptor myConceptURLValidation = createDescriptorForURLValidation();
  /*package*/ final ConceptDescriptor myConceptValidation = createDescriptorForValidation();
  /*package*/ final ConceptDescriptor myConceptWaitPageContainsElement = createDescriptorForWaitPageContainsElement();
  /*package*/ final ConceptDescriptor myConceptWebPage = createDescriptorForWebPage();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptAction, myConceptAndOfAciton, myConceptClick, myConceptInputText, myConceptLogicOfActions, myConceptMaximize, myConceptOrOfAction, myConceptPageContainValidation, myConceptTestCase, myConceptTestSuite, myConceptURLValidation, myConceptValidation, myConceptWaitPageContainsElement, myConceptWebPage);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Action:
        return myConceptAction;
      case LanguageConceptSwitch.AndOfAciton:
        return myConceptAndOfAciton;
      case LanguageConceptSwitch.Click:
        return myConceptClick;
      case LanguageConceptSwitch.InputText:
        return myConceptInputText;
      case LanguageConceptSwitch.LogicOfActions:
        return myConceptLogicOfActions;
      case LanguageConceptSwitch.Maximize:
        return myConceptMaximize;
      case LanguageConceptSwitch.OrOfAction:
        return myConceptOrOfAction;
      case LanguageConceptSwitch.PageContainValidation:
        return myConceptPageContainValidation;
      case LanguageConceptSwitch.TestCase:
        return myConceptTestCase;
      case LanguageConceptSwitch.TestSuite:
        return myConceptTestSuite;
      case LanguageConceptSwitch.URLValidation:
        return myConceptURLValidation;
      case LanguageConceptSwitch.Validation:
        return myConceptValidation;
      case LanguageConceptSwitch.WaitPageContainsElement:
        return myConceptWaitPageContainsElement;
      case LanguageConceptSwitch.WebPage:
        return myConceptWebPage;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "Action", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b4L);
    b.class_(false, true, false);
    // extends: DSL_UITesting.structure.LogicOfActions
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/6810867076138230196");
    b.version(3);
    b.alias("action");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForAndOfAciton() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "AndOfAciton", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x65da7a46226281c6L);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.LogicOfActions
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/7339312984396825030");
    b.version(3);
    b.aggregate("logicActions", 0x65da7a46226299d3L).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL).optional(true).ordered(true).multiple(true).origin("7339312984396831187").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForClick() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "Click", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61bdL);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.Action
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b4L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/6810867076138230205");
    b.version(3);
    b.property("target", 0x5e850f852d9f61bfL).type(PrimitiveTypeId.STRING).origin("6810867076138230207").done();
    b.alias("click");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputText() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "InputText", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b7L);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.Action
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b4L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/6810867076138230199");
    b.version(3);
    b.property("target", 0x5e850f852d9f61bbL).type(PrimitiveTypeId.STRING).origin("6810867076138230203").done();
    b.property("text", 0x612d5369b4c91e1cL).type(PrimitiveTypeId.STRING).origin("7002344709100740124").done();
    b.alias("input");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForLogicOfActions() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "LogicOfActions", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL);
    b.class_(false, true, false);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/4459806475702226378");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForMaximize() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "Maximize", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x55f23646c34291c3L);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.Action
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b4L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/6193072115139383747");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOrOfAction() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "OrOfAction", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdc6L);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.LogicOfActions
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/4459806475702226374");
    b.version(3);
    b.aggregate("logicActions", 0x3de46a5c4f37cdccL).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL).optional(true).ordered(true).multiple(true).origin("4459806475702226380").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForPageContainValidation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "PageContainValidation", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198c5L);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.Validation
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198c3L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/1653476194101860549");
    b.version(3);
    b.property("text", 0x16f253d68a0198c9L).type(PrimitiveTypeId.STRING).origin("1653476194101860553").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestCase() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "TestCase", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/6810867076138230210");
    b.version(3);
    b.aggregate("LogicOfActions", 0x65da7a46226712cfL).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdcaL).optional(true).ordered(true).multiple(true).origin("7339312984397124303").done();
    b.aggregate("validations", 0x16f253d68a0198beL).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198c3L).optional(true).ordered(true).multiple(true).origin("1653476194101860542").done();
    b.alias("testcase");
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForTestSuite() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "TestSuite", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198b1L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/1653476194101860529");
    b.version(3);
    b.aggregate("webpage", 0x16f253d68a0198b3L).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61cdL).optional(false).ordered(true).multiple(false).origin("1653476194101860531").done();
    b.aggregate("valid", 0x16f253d68a0198b5L).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L).optional(true).ordered(true).multiple(true).origin("1653476194101860533").done();
    b.aggregate("invalid", 0x16f253d68a0198b9L).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L).optional(true).ordered(true).multiple(true).origin("1653476194101860537").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForURLValidation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "URLValidation", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x4c1f89def2610acaL);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.Validation
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198c3L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/5485254461802744522");
    b.version(3);
    b.property("correctURL", 0x4c1f89def2611067L).type(PrimitiveTypeId.STRING).origin("5485254461802745959").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForValidation() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "Validation", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198c3L);
    b.class_(false, true, false);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/1653476194101860547");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWaitPageContainsElement() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "WaitPageContainsElement", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x713bab4a4f9d11d8L);
    b.class_(false, false, false);
    // extends: DSL_UITesting.structure.Action
    b.super_(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b4L);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/8159303485563408856");
    b.version(3);
    b.property("locator", 0x713bab4a4f9d11dbL).type(PrimitiveTypeId.STRING).origin("8159303485563408859").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForWebPage() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("DSL_UITesting", "WebPage", 0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61cdL);
    b.class_(false, false, false);
    b.origin("r:a8a7db01-62f2-42ed-bf22-7d6670abf5f4(DSL_UITesting.structure)/6810867076138230221");
    b.version(3);
    b.property("url", 0x5e850f852d9f61cfL).type(PrimitiveTypeId.STRING).origin("6810867076138230223").done();
    b.alias("webpage");
    return b.create();
  }
}
