package Testing_Resources.generator.templates;

/*Generated by MPS */

import jetbrains.mps.generator.runtime.Generated;
import jetbrains.mps.generator.impl.query.QueryProviderBase;
import jetbrains.mps.generator.template.PropertyMacroContext;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.generator.template.SourceSubstituteMacroNodesContext;
import java.util.Map;
import jetbrains.mps.generator.impl.query.SourceNodesQuery;
import java.util.HashMap;
import org.jetbrains.annotations.NotNull;
import jetbrains.mps.generator.impl.query.QueryKey;
import java.util.Collection;
import jetbrains.mps.generator.impl.GenerationFailureException;
import jetbrains.mps.util.IterableUtil;
import jetbrains.mps.generator.impl.query.PropertyValueQuery;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SProperty;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SContainmentLink;

@Generated
public class QueriesGenerated extends QueryProviderBase {
  public QueriesGenerated() {
    super(1);
  }
  public static Object propertyMacro_GetValue_1_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.target$VrP7);
  }
  public static Object propertyMacro_GetValue_1_1(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.text$InNF);
  }
  public static Object propertyMacro_GetValue_2_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.target$VxT_);
  }
  public static Object propertyMacro_GetValue_4_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(SLinkOperations.getTarget(_context.getNode(), LINKS.webpage$c5Cq), PROPS.url$VJW_);
  }
  public static Object propertyMacro_GetValue_5_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.name$MnvL);
  }
  public static Object propertyMacro_GetValue_6_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.correctURL$4lSa);
  }
  public static Object propertyMacro_GetValue_7_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.text$cl7s);
  }
  public static Object propertyMacro_GetValue_8_0(final PropertyMacroContext _context) {
    return SPropertyOperations.getString(_context.getNode(), PROPS.locator$G4wA);
  }
  public static Iterable<SNode> sourceNodesQuery_4_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.valid$c66s);
  }
  public static Iterable<SNode> sourceNodesQuery_4_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.invalid$c72w);
  }
  public static Iterable<SNode> sourceNodesQuery_5_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.LogicOfActions$CP6j);
  }
  public static Iterable<SNode> sourceNodesQuery_5_1(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.validations$1GnT);
  }
  public static Iterable<SNode> sourceNodesQuery_9_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.logicActions$3zhb);
  }
  public static Iterable<SNode> sourceNodesQuery_10_0(final SourceSubstituteMacroNodesContext _context) {
    return SLinkOperations.getChildren(_context.getNode(), LINKS.logicActions$ycmY);
  }
  private final Map<String, SourceNodesQuery> snsqMethods = new HashMap<String, SourceNodesQuery>();
  {
    int i = 0;
    snsqMethods.put("1976252372492163292", new SNsQ(i++));
    snsqMethods.put("1976252372492410241", new SNsQ(i++));
    snsqMethods.put("7339312984397253417", new SNsQ(i++));
    snsqMethods.put("5419241583358856985", new SNsQ(i++));
    snsqMethods.put("7339312984397039300", new SNsQ(i++));
    snsqMethods.put("6362081607029669255", new SNsQ(i++));
  }
  @NotNull
  @Override
  public SourceNodesQuery getSourceNodesQuery(@NotNull QueryKey identity) {
    SourceNodesQuery query = identity.forFunctionNode(snsqMethods);
    return (query != null ? query : super.getSourceNodesQuery(identity));
  }
  private static class SNsQ implements SourceNodesQuery {
    private final int methodKey;
    public SNsQ(int methodKey) {
      this.methodKey = methodKey;
    }
    @NotNull
    public Collection<SNode> evaluate(@NotNull SourceSubstituteMacroNodesContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_0(ctx));
        case 1:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_4_1(ctx));
        case 2:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_0(ctx));
        case 3:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_5_1(ctx));
        case 4:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_9_0(ctx));
        case 5:
          return IterableUtil.asCollection(QueriesGenerated.sourceNodesQuery_10_0(ctx));
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }
  private final Map<String, PropertyValueQuery> pvqMethods = new HashMap<String, PropertyValueQuery>();
  {
    int i = 0;
    pvqMethods.put("6540601560108699613", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "locator"));
    pvqMethods.put("403501991463725297", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), null));
    pvqMethods.put("6540601560108710537", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "locator"));
    pvqMethods.put("1976252372491945584", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), null));
    pvqMethods.put("8834186762294931882", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), null));
    pvqMethods.put("5419241583358858650", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), null));
    pvqMethods.put("8159303485563299142", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "ele"));
    pvqMethods.put("8159303485563409148", new PVQ(i++, MetaAdapterFactory.getProperty(0x479c7a8c02f943b5L, 0x9139d910cb22f298L, 0x16838b3fce9aa513L, 0x16838b3fce9aaa68L, "value"), "loc"));
  }
  @NotNull
  @Override
  public PropertyValueQuery getPropertyValueQuery(@NotNull QueryKey identity) {
    PropertyValueQuery query = identity.forTemplateNode(pvqMethods);
    return (query != null ? query : super.getPropertyValueQuery(identity));
  }
  private static class PVQ extends PropertyValueQuery.Base {
    private final int methodKey;
    /*package*/ PVQ(int methodKey, SProperty property, String templateValue) {
      super(property, templateValue);
      this.methodKey = methodKey;
    }
    @Nullable
    public Object evaluate(@NotNull PropertyMacroContext ctx) throws GenerationFailureException {
      switch (methodKey) {
        case 0:
          return QueriesGenerated.propertyMacro_GetValue_1_0(ctx);
        case 1:
          return QueriesGenerated.propertyMacro_GetValue_1_1(ctx);
        case 2:
          return QueriesGenerated.propertyMacro_GetValue_2_0(ctx);
        case 3:
          return QueriesGenerated.propertyMacro_GetValue_4_0(ctx);
        case 4:
          return QueriesGenerated.propertyMacro_GetValue_5_0(ctx);
        case 5:
          return QueriesGenerated.propertyMacro_GetValue_6_0(ctx);
        case 6:
          return QueriesGenerated.propertyMacro_GetValue_7_0(ctx);
        case 7:
          return QueriesGenerated.propertyMacro_GetValue_8_0(ctx);
        default:
          throw new GenerationFailureException(String.format("Inconsistent QueriesGenerated: there's no method for query %s (key: #%d)", ctx.getTemplateReference(), methodKey));
      }
    }
  }

  private static final class PROPS {
    /*package*/ static final SProperty target$VrP7 = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b7L, 0x5e850f852d9f61bbL, "target");
    /*package*/ static final SProperty text$InNF = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61b7L, 0x612d5369b4c91e1cL, "text");
    /*package*/ static final SProperty target$VxT_ = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61bdL, 0x5e850f852d9f61bfL, "target");
    /*package*/ static final SProperty url$VJW_ = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61cdL, 0x5e850f852d9f61cfL, "url");
    /*package*/ static final SProperty name$MnvL = MetaAdapterFactory.getProperty(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L, 0x110396ec041L, "name");
    /*package*/ static final SProperty correctURL$4lSa = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x4c1f89def2610acaL, 0x4c1f89def2611067L, "correctURL");
    /*package*/ static final SProperty text$cl7s = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198c5L, 0x16f253d68a0198c9L, "text");
    /*package*/ static final SProperty locator$G4wA = MetaAdapterFactory.getProperty(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x713bab4a4f9d11d8L, 0x713bab4a4f9d11dbL, "locator");
  }

  private static final class LINKS {
    /*package*/ static final SContainmentLink webpage$c5Cq = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198b1L, 0x16f253d68a0198b3L, "webpage");
    /*package*/ static final SContainmentLink valid$c66s = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198b1L, 0x16f253d68a0198b5L, "valid");
    /*package*/ static final SContainmentLink invalid$c72w = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x16f253d68a0198b1L, 0x16f253d68a0198b9L, "invalid");
    /*package*/ static final SContainmentLink LogicOfActions$CP6j = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L, 0x65da7a46226712cfL, "LogicOfActions");
    /*package*/ static final SContainmentLink validations$1GnT = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L, 0x16f253d68a0198beL, "validations");
    /*package*/ static final SContainmentLink logicActions$3zhb = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x65da7a46226281c6L, 0x65da7a46226299d3L, "logicActions");
    /*package*/ static final SContainmentLink logicActions$ycmY = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x3de46a5c4f37cdc6L, 0x3de46a5c4f37cdccL, "logicActions");
  }
}
