package Keyword_Testing_Resources.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptTestCaseRef = createDescriptorForTestCaseRef();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptTestCaseRef);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.TestCaseRef:
        return myConceptTestCaseRef;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForTestCaseRef() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("Keyword_Testing_Resources", "TestCaseRef", 0xab99a4df0f83455bL, 0xbfc425eb0198dd5fL, 0x5e850f852d9f6e27L);
    b.class_(false, false, true);
    b.origin("r:02bd8420-78fc-4c1f-8525-54e0e2d21b10(Keyword_Testing_Resources.structure)/6810867076138233383");
    b.version(3);
    b.associate("testcase", 0x5e850f852d9f6e28L).target(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L).optional(false).origin("6810867076138233384").done();
    return b.create();
  }
}
