package Testing_Resources_Scripts.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenDescriptorBase;
import jetbrains.mps.text.rt.TextGenContext;
import jetbrains.mps.text.impl.TextGenSupport;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.internal.collections.runtime.IVisitor;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SReferenceLink;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import org.jetbrains.mps.openapi.language.SContainmentLink;

public class TestCaseRef_TextGen extends TextGenDescriptorBase {
  @Override
  public void generateText(final TextGenContext ctx) {
    final TextGenSupport tgs = new TextGenSupport(ctx);
    ListSequence.fromList(SLinkOperations.getChildren(SLinkOperations.getTarget(ctx.getPrimaryInput(), LINKS.testcase$cH08), LINKS.actions$VCEB)).visitAll(new IVisitor<SNode>() {
      public void visit(SNode it) {
        tgs.appendNode(it);

      }
    });
  }

  private static final class LINKS {
    /*package*/ static final SReferenceLink testcase$cH08 = MetaAdapterFactory.getReferenceLink(0x6d3b6fdf2c19420aL, 0xaf23ac75f8ecd209L, 0x5e850f852da0287bL, 0x5e850f852da0287eL, "testcase");
    /*package*/ static final SContainmentLink actions$VCEB = MetaAdapterFactory.getContainmentLink(0xd46317ec6b314005L, 0x8773ee03f2c019d7L, 0x5e850f852d9f61c2L, 0x5e850f852d9f61c6L, "actions");
  }
}
