package Testing_Resources_Scripts.textGen;

/*Generated by MPS */

import jetbrains.mps.text.rt.TextGenAspectBase;
import Testing_Resources_Scripts.structure.LanguageConceptSwitch;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.text.rt.TextGenDescriptor;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.text.rt.TextGenModelOutline;
import org.jetbrains.mps.openapi.model.SNode;
import org.jetbrains.mps.openapi.language.SConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;

public class TextGenAspectDescriptor extends TextGenAspectBase {
  private final LanguageConceptSwitch myIndex = new LanguageConceptSwitch();

  public TextGenAspectDescriptor() {
  }

  @Nullable
  @Override
  public TextGenDescriptor getDescriptor(@NotNull SAbstractConcept concept) {
    switch (myIndex.index(concept)) {
      case LanguageConceptSwitch.TestCaseRef:
        return new TestCaseRef_TextGen();
    }
    return null;
  }

  @Override
  public void breakdownToUnits(@NotNull TextGenModelOutline outline) {
    for (SNode root : outline.getModel().getRootNodes()) {
      if (root.getConcept().equals(CONCEPTS.TestCaseRef$UC)) {
        String fname = getFileName_TestCaseRef(root);
        String ext = getFileExtension_TestCaseRef(root);
        outline.registerTextUnit((ext == null ? fname : (fname + '.' + ext)), root);
        continue;
      }
    }
  }
  private static String getFileName_TestCaseRef(SNode node) {
    return node.getName();
  }
  private static String getFileExtension_TestCaseRef(SNode node) {
    return "json";
  }

  private static final class CONCEPTS {
    /*package*/ static final SConcept TestCaseRef$UC = MetaAdapterFactory.getConcept(0x6d3b6fdf2c19420aL, 0xaf23ac75f8ecd209L, 0x5e850f852da0287bL, "Testing_Resources_Scripts.structure.TestCaseRef");
  }
}
